

#ifndef _BRSHW_PORTS_H_
#define _BRSHW_PORTS_H_

typedef enum{
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTGROUP_6,
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTGROUP_9,
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTGROUP_12,
  BRSHW_PORT_PORTGROUP_13,
  BRSHW_PORT_PORTGROUP_14,
  BRSHW_PORT_PORTGROUP_15,
  BRSHW_PORT_PORTGROUP_16,
  BRSHW_PORT_PORTGROUP_17,
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTGROUP_19,
  BRSHW_PORT_PORTGROUP_20
}brsHw_Port_PortGroupType;

typedef enum{
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_PORTNUMBER_15,
  BRSHW_PORT_PORTNUMBER_16
}brsHw_Port_PortNumberType;

typedef enum{
  BRSHW_PORT_ALT_0,
  BRSHW_PORT_ALT_1,
  BRSHW_PORT_ALT_2,
  BRSHW_PORT_ALT_3,
  BRSHW_PORT_ALT_4,
  BRSHW_PORT_ALT_5,
  BRSHW_PORT_ALT_6,
  BRSHW_PORT_ALT_7
}brsHw_Port_AlternativeType;

typedef enum{
  PORT_PULL_UP_DISABLED,
  PORT_PULL_UP_ENABLED
}brsHw_Port_PullUpOption;

typedef enum{
  PORT_DRIVE_STRENGTH_CONTROL_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED
}brsHw_Port_PortDriveStrength;

typedef enum{
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_OPEN_DRAIN_CONTROL_ENABLED
}brsHw_Port_PortOpenDrainControl;

typedef enum{
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_ENABLED
}brsHw_Port_InputBufferSelect;

typedef enum{
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED
}brsHw_Port_PortProtectionCommand;

typedef enum{
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_PROTECTION_STATUS_ENABLED
}brsHw_Port_PortProtectionStatus;

typedef enum{
  PORT_IP_CONTROL_DISABLED,
  PORT_IP_CONTROL_ENABLED
}brsHw_Port_PortIPControl;

typedef enum{
  PORT_BIDIRECTIONAL_MODE_DISABLED,
  PORT_BIDIRECTIONAL_MODE_ENABLED
}brsHw_Port_BidirectionalMode;

typedef struct{
  brsHw_Port_PortGroupType   portGroup;
  brsHw_Port_PortNumberType  portNumber;
  brsHw_Port_AlternativeType portAlternative;
}brsHw_Port_PortType;

typedef struct{
  brsHw_Port_PullUpOption           PortPullUp;
  brsHw_Port_PortDriveStrength      PortDriveStrength;
  brsHw_Port_PortOpenDrainControl   PortOpenDrain;
  brsHw_Port_InputBufferSelect      PortInputBuffer;
  brsHw_Port_PortProtectionCommand  PortProtectionCMD;
  brsHw_Port_PortProtectionStatus   PortProtectionStatus;
  brsHw_Port_PortIPControl          PortIPControl;
  brsHw_Port_BidirectionalMode      PortBidirectionalMode;
}brsHw_Port_ConfType;

#define BRSHW_PORT_LOGIC_HIGH (uint8)1
#define BRSHW_PORT_LOGIC_LOW  (uint8)0

#if defined (BRS_ENABLE_TCM_SUPPORT)
# if defined (BRSHW_PORT_GROUP_A)
#  if defined (BRS_EVA_BOARD_F1X_176PIN) || defined (BRS_EVA_BOARD_F1X_144PIN) || \
      defined (BRS_EVA_BOARD_F1X_064PIN) || defined (BRS_EVA_BOARD_F1X_100PIN)
const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_OUT = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType  BRSHW_PORT_TCM_SDA_IN = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_OUT = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_IN = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_0};

#  else

const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_OUT = {
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_IN = {
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_OUT = {
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_IN = {
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_0};

#   if 0

const brsHw_Port_PortType BRSHW_PORT_TCM_INTA_IN = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_TCM_INTB_IN = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_5};
#   endif
#  endif

# elif defined (BRSHW_PORT_GROUP_B)
#  if defined (BRS_EVA_BOARD_P1X_144PIN) || defined (BRS_EVA_BOARD_P1X_100PIN)
const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_OUT = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType  BRSHW_PORT_TCM_SDA_IN = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_OUT = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_IN = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_0};

#  else
const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_OUT = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType  BRSHW_PORT_TCM_SDA_IN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_OUT = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_IN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_0};
#  endif

# elif defined (BRSHW_PORT_GROUP_B2)
#  if defined (BRS_EVA_BOARD_P1XC_292PIN)
const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_OUT = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_15,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType  BRSHW_PORT_TCM_SDA_IN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_OUT = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_IN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_0};

 #  elif defined (BRS_EVA_BOARD_P1XC_80PIN)
const brsHw_Port_PortType BRSHW_PORT_TCM_SDA_OUT = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType  BRSHW_PORT_TCM_SDA_IN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_OUT = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_TCM_CLK_IN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_0};
#  endif

# else
  #error "TCM-Ports for your environment not yet configured within BrsHw_Ports.h. Configure them or disable BRS_ENABLE_TCM_SUPPORT."
# endif
#endif

#if defined (BRS_ENABLE_SUPPORT_LEDS)
# if !defined (VGEN_ENABLE_DRVPORT)
#  if defined (BRS_EVA_BOARD_DEFAULT)

const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_VEN001092)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_11
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_VEN001099) || defined (BRS_EVA_BOARD_MANGO)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_16,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_VEBN01283)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_VEBN01326)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_VEN001220) || defined (BRS_EVA_BOARD_VEN001243)

const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_6,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_F1X_176PIN) || defined (BRS_EVA_BOARD_F1X_144PIN) || \
        defined (BRS_EVA_BOARD_F1X_064PIN) || defined (BRS_EVA_BOARD_F1X_100PIN)

const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_P1XC_292PIN)

const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_6,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_HSR_715) || defined (BRS_EVA_BOARD_HSR_1502)

const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_P1X_144PIN)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_P1X_100PIN)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_0};

#  elif defined (BRS_EVA_BOARD_P1XC_80PIN)
const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_0};

#  else

const brsHw_Port_PortType BRSHW_PORT_LED = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_0 };

#  endif

# else
  #error "Configure the valid PortPin for the LED within your DrvPort config and uncomment this error. Or disable BRS_ENABLE_SUPPORT_LEDS."
# endif
#endif

#if defined (BRS_ENABLE_SUPPORT_TOGGLE_WD_PIN)
# if defined (BRS_ENABLE_FBL_SUPPORT)
  #define BRS_START_SEC_RAM_CONST
  #include "Brs_MemMap.hpp"
# endif

const brsHw_Port_PortType BRSHW_PORT_TOGGLE_WD = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_0 };

# if defined (BRS_ENABLE_FBL_SUPPORT)
  #define BRS_STOP_SEC_RAM_CONST
  #include "Brs_MemMap.hpp"
# endif
#endif

#if defined (BRS_ENABLE_SUPPORT_TOGGLE_CUSTOM_PIN)
  #error "Please configure here the needed custom toggle pin and uncomment this error, or disable BRS_ENABLE_SUPPORT_TOGGLE_CUSTOM_PIN"*/

const brsHw_Port_PortType BRSHW_PORT_TOGGLE_CUSTOM = {
  BRSHW_PORT_PORTGROUP_x,
  BRSHW_PORT_PORTNUMBER_x,
  BRSHW_PORT_ALT_x};
#endif

#if defined (VGEN_ENABLE_LIN_DRV)
const brsHw_Port_ConfType BRSHW_PORT_CONF_LIN = {
  PORT_PULL_UP_ENABLED,
  PORT_DRIVE_STRENGTH_CONTROL_DISABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
#endif

#if defined (VGEN_ENABLE_DRVETH__BASEASR)
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0TXD = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0TXEN = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0TXERR = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0MDC = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0MDIO = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_ENABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
#endif

#if defined (BRSHW_PORT_GROUP_A)

# if defined (VGEN_ENABLE_CAN_DRV)
#  if defined (BRS_EVA_BOARD_HSR_1502)
  #define _BRSHW_PORT_CAN0_TRCV_EN
  #define _BRSHW_PORT_CAN1_TRCV_EN

const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_CAN0_TRCV_EN = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_0};

const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN1_TRCV_EN = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_0};

#  else
const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_2};

const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_2};
#  endif

const brsHw_Port_PortType BRSHW_PORT_CAN2_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_1 };
const brsHw_Port_PortType BRSHW_PORT_CAN2_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_1 };

const brsHw_Port_PortType BRSHW_PORT_CAN3_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_CAN3_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_1};

const brsHw_Port_PortType BRSHW_PORT_CAN4_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN4_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_5};

const brsHw_Port_PortType BRSHW_PORT_CAN5_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN5_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_5};
# endif

# if defined (VGEN_ENABLE_LIN_DRV)
const brsHw_Port_PortType BRSHW_PORT_LIN2_0_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN2_0_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN2_1_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_1_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_2_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_LIN2_2_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_LIN2_3_TX = {
  BRSHW_PORT_PORTGROUP_20,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_3_RX = {
  BRSHW_PORT_PORTGROUP_20,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_4_TX = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_4_RX = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_5_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_5_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_6_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_6_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_7_TX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_7_RX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_0};
const brsHw_Port_PortType BRSHW_PORT_LIN2_8_TX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_8_RX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_9_TX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN2_9_RX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_TX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_RX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_2_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_2_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_3_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_3_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_4_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_4_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_5_TX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_5_RX = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_1};
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)
const brsHw_Port_PortType BRSHW_PORT_FLX0_A_TX = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_FLX0_A_EN = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX0_A_RX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_2};

const brsHw_Port_PortType BRSHW_PORT_FLX0_B_TX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX0_B_EN = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX0_B_RX = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_6};
# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)
#  if(defined BRS_EVA_BOARD_VEBN00970)
  #define BRSHW_PORT_ETH0_RESET
const brsHw_Port_PortType BRSHW_PORT_ETH0RESET = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_0};
#  endif
const brsHw_Port_PortType BRSHW_PORT_ETH0TXCLK = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD0 = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD1 = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD2 = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD3 = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXEN = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXERR = {
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXCLK = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_6};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD0 = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_6};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD1 = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_6};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD2 = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_6};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD3 = {
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_6};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXDV = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXERR = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_ETH0CRS = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_ETH0COL = {
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_ETH0MDIO = {
  BRSHW_PORT_PORTGROUP_12,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_ETH0MDC = {
  BRSHW_PORT_PORTGROUP_12,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_2};
# endif
#endif

#if defined (BRSHW_PORT_GROUP_B)

# if defined (VGEN_ENABLE_CAN_DRV)
const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_CAN2_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_CAN2_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_1};

#  if defined (kCanPhysToLogChannelIndex_3) ||defined (kCanPhysToLogChannelIndex_4) || \
      defined (kCanPhysToLogChannelIndex_5)
  #error "Port config for these CAN channels not yet implemented yet!"
#  endif
# endif

# if defined (VGEN_ENABLE_LIN_DRV)
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_TX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_RX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_TX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_RX = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_3};
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)
const brsHw_Port_PortType BRSHW_PORT_FLX0_A_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_FLX0_A_EN = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_FLX0_A_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_FLX0_B_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_FLX0_B_EN = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_FLX0_B_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_5};
# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)
  #error "Port config for ETHERNET not yet implemented for Port Group B!"
# endif
#endif

#if defined (BRSHW_PORT_GROUP_B1)

# if defined (VGEN_ENABLE_CAN_DRV)
const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN0_WAKEUP = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_7};
const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_15,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN1_WAKEUP = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_7};
const brsHw_Port_PortType BRSHW_PORT_CAN2_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN2_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN2_WAKEUP = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_7};
const brsHw_Port_PortType BRSHW_PORT_CAN3_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN3_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN3_WAKEUP = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_7};
# endif

# if defined (VGEN_ENABLE_LIN_DRV)
const brsHw_Port_PortType BRSHW_PORT_LIN2_0_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_0_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_1_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_1_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_2_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_2_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_4};
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)
  #error "Port config for FLEXRAY not yet implemented for Port Group B1!"
# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)
  #error "Port config for ETHERNET not yet implemented for Port Group B1!"
# endif
#endif

#if defined (BRSHW_PORT_GROUP_B2)

# if defined (VGEN_ENABLE_CAN_DRV)
#  if defined (BRS_EVA_BOARD_VEN001265)
 const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_3};
 const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_3};
#  else
 const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_3};
 const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_4};
#  endif
const brsHw_Port_PortType BRSHW_PORT_CAN0_WAKEUP = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN1_WAKEUP = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN2_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN2_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN2_WAKEUP = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN3_TX = {
  BRSHW_PORT_PORTGROUP_9,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN3_RX = {
  BRSHW_PORT_PORTGROUP_9,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_CAN3_WAKEUP = {
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_2};
# endif

# if defined (VGEN_ENABLE_LIN_DRV)
#  if defined (BRS_EVA_BOARD_VEN001265)
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_3};
#  else
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_2};
#  endif
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_2_TX = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_2_RX = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_3_TX = {
  BRSHW_PORT_PORTGROUP_9,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_3_RX = {
  BRSHW_PORT_PORTGROUP_9,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_4};
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)

const brsHw_Port_PortType BRSHW_PORT_FLX0_TX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_FLX0_EN = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_FLX0_RX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_4};

const brsHw_Port_PortType BRSHW_PORT_FLX0_TX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_FLX0_EN = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_FLX0_RX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_4};

# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)
  #error "Please choose if you want to use ethernet channel 0 or 1"
#  if defined (BRS_EVA_BOARD_VEN001265)
  #define BRSHW_PORT_ETH0_RESET
const brsHw_Port_PortType BRSHW_PORT_ETH0RESET = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_0};
#  endif

const brsHw_Port_PortType BRSHW_PORT_ETH0TXCLK = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD0 = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD1 = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD2 = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD3 = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXEN = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXERR = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXCLK = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD0 = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD1 = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD2 = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD3 = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXDV = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXER = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0CRS = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0COL = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0MDIO = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0MDC = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_2};

# endif
#endif

#if defined (BRSHW_PORT_GROUP_C)

# if defined (VGEN_ENABLE_CAN_DRV)
const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_4};
  const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_CAN2_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_CAN2_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_4};
# endif

# if defined (VGEN_ENABLE_LIN_DRV)
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_2_TX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_2_RX = {
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_LIN3_3_TX = {
  BRSHW_PORT_PORTGROUP_44,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_3_RX = {
  BRSHW_PORT_PORTGROUP_44,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)
  #error "Port config for FLEXRAY not yet implemented for Port Group C!"
# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)

const brsHw_Port_PortType BRSHW_PORT_ETH0TXCLK = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD0 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD1 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD2 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXD3 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0TXEN = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_1};

#  if !defined (BRS_EVA_BOARD_MANGO)

const brsHw_Port_PortType BRSHW_PORT_ETH0TXERR = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0COL = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0CRS = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXERR = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_15,
  BRSHW_PORT_ALT_1};
#  endif

const brsHw_Port_PortType BRSHW_PORT_ETH0RXCLK = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD0 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD1 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD2 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_ALT_1};
const brsHw_Port_PortType BRSHW_PORT_ETH0RXD3 = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_1};

const brsHw_Port_PortType BRSHW_PORT_ETH0RXDV = {
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_ALT_1};

#  if defined (BRS_EVA_BOARD_MANGO)
const brsHw_Port_PortType BRSHW_PORT_ETH0MDIO = {
  BRSHW_PORT_PORTGROUP_47,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_ETH0MDC = {
  BRSHW_PORT_PORTGROUP_47,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};
#  endif

# endif
#endif

#if defined (BRSHW_PORT_GROUP_D)

# if defined (VGEN_ENABLE_CAN_DRV)
const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN0_WAKEUP = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_7};
const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN1_WAKEUP = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_7};
const brsHw_Port_PortType BRSHW_PORT_CAN2_TX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN2_RX = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN2_WAKEUP = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_7};
const brsHw_Port_PortType BRSHW_PORT_CAN3_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN3_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_5};
const brsHw_Port_PortType BRSHW_PORT_CAN3_WAKEUP = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_7};
# endif

# if defined (VGEN_ENABLE_LIN_DRV)
const brsHw_Port_PortType BRSHW_PORT_LIN2_8_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN2_8_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_4};
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)
  #error "Port config for FLEXRAY not yet implemented for Port Group D!"
# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)
  #error "Port config for ETHERNET not yet implemented for Port Group D!"
# endif
#endif

#if defined (BRSHW_PORT_GROUP_F)

# if defined (VGEN_ENABLE_CAN_DRV)
#  if defined (BRS_EVA_BOARD_P1XC_80PIN)
 const brsHw_Port_PortType BRSHW_PORT_CAN0_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_3};
 const brsHw_Port_PortType BRSHW_PORT_CAN0_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN0_WAKEUP = {
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};

const brsHw_Port_PortType BRSHW_PORT_CAN1_TX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN1_RX = {
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_3};
const brsHw_Port_PortType BRSHW_PORT_CAN1_WAKEUP = {
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_3};

#  else
   #error "Wrong Eval board selected for CAN driver setup. Currently supported: BRS_EVA_BOARD_P1XC_80PIN"
#  endif

# endif

# if defined (VGEN_ENABLE_LIN_DRV)
#  if defined (BRS_EVA_BOARD_P1XC_80PIN)
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_0_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_TX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_4};
const brsHw_Port_PortType BRSHW_PORT_LIN3_1_RX = {
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_ALT_4};
#  else
   #error "Wrong Eval board selected for LIN driver setup. Currently supported: BRS_EVA_BOARD_P1XC_80PIN"
#  endif
# endif

# if defined (VGEN_ENABLE_DRVFR__BASEASR)
  #error "Port config for FLEXRAY not yet implemented for Port Group F!"
# endif

# if defined (VGEN_ENABLE_DRVETH__BASEASR)
  #error "Port config for ETHERNET not yet implemented for Port Group F!"
# endif
#endif

#endif
