

#define FBL_MEMMAP_ERROR

#if defined( CANIF_START_SEC_APPL_CODE )

# undef CANIF_START_SEC_APPL_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_APPL_CODE )

# undef CANIF_STOP_SEC_APPL_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CODE )

# undef CANIF_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CODE )

# undef CANIF_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_16BIT )

# undef CANIF_START_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_16BIT )

# undef CANIF_STOP_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_32BIT )

# undef CANIF_START_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_32BIT )

# undef CANIF_STOP_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_8BIT )

# undef CANIF_START_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_8BIT )

# undef CANIF_STOP_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_FAST_16BIT )

# undef CANIF_START_SEC_CONST_FAST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_FAST_16BIT )

# undef CANIF_STOP_SEC_CONST_FAST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_FAST_32BIT )

# undef CANIF_START_SEC_CONST_FAST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_FAST_32BIT )

# undef CANIF_STOP_SEC_CONST_FAST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_FAST_8BIT )

# undef CANIF_START_SEC_CONST_FAST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_FAST_8BIT )

# undef CANIF_STOP_SEC_CONST_FAST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_FAST_UNSPECIFIED )

# undef CANIF_START_SEC_CONST_FAST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_FAST_UNSPECIFIED )

# undef CANIF_STOP_SEC_CONST_FAST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_CONST_UNSPECIFIED )

# undef CANIF_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_CONST_UNSPECIFIED )

# undef CANIF_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_PBCFG )

# undef CANIF_START_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_PBCFG )

# undef CANIF_STOP_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_INIT_16BIT )

# undef CANIF_START_SEC_VAR_FAST_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_INIT_16BIT )

# undef CANIF_STOP_SEC_VAR_FAST_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_INIT_32BIT )

# undef CANIF_START_SEC_VAR_FAST_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_INIT_32BIT )

# undef CANIF_STOP_SEC_VAR_FAST_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_INIT_8BIT )

# undef CANIF_START_SEC_VAR_FAST_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_INIT_8BIT )

# undef CANIF_STOP_SEC_VAR_FAST_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_INIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_FAST_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_NOINIT_16BIT )

# undef CANIF_START_SEC_VAR_FAST_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_NOINIT_16BIT )

# undef CANIF_STOP_SEC_VAR_FAST_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_NOINIT_32BIT )

# undef CANIF_START_SEC_VAR_FAST_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_NOINIT_32BIT )

# undef CANIF_STOP_SEC_VAR_FAST_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_NOINIT_8BIT )

# undef CANIF_START_SEC_VAR_FAST_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_NOINIT_8BIT )

# undef CANIF_STOP_SEC_VAR_FAST_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_ZERO_INIT_16BIT )

# undef CANIF_START_SEC_VAR_FAST_ZERO_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_16BIT )

# undef CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_ZERO_INIT_32BIT )

# undef CANIF_START_SEC_VAR_FAST_ZERO_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_32BIT )

# undef CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_ZERO_INIT_8BIT )

# undef CANIF_START_SEC_VAR_FAST_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT )

# undef CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_INIT_16BIT )

# undef CANIF_START_SEC_VAR_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_INIT_16BIT )

# undef CANIF_STOP_SEC_VAR_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_INIT_32BIT )

# undef CANIF_START_SEC_VAR_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_INIT_32BIT )

# undef CANIF_STOP_SEC_VAR_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_INIT_8BIT )

# undef CANIF_START_SEC_VAR_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_INIT_8BIT )

# undef CANIF_STOP_SEC_VAR_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_INIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_INIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_INIT_16BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_INIT_16BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_INIT_32BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_INIT_32BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_INIT_8BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_INIT_8BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_INIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_NOCACHE_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_INIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_NOCACHE_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_NOINIT_16BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_16BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_NOINIT_32BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_32BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_NOINIT_8BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_8BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_NOCACHE_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_16BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_16BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_32BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_32BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_8BIT )

# undef CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_8BIT )

# undef CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_NOCACHE_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOINIT_16BIT )

# undef CANIF_START_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOINIT_16BIT )

# undef CANIF_STOP_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOINIT_32BIT )

# undef CANIF_START_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOINIT_32BIT )

# undef CANIF_STOP_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOINIT_8BIT )

# undef CANIF_START_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOINIT_8BIT )

# undef CANIF_STOP_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_PBCFG )

# undef CANIF_START_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_PBCFG )

# undef CANIF_STOP_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_ZERO_INIT_16BIT )

# undef CANIF_START_SEC_VAR_ZERO_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_ZERO_INIT_16BIT )

# undef CANIF_STOP_SEC_VAR_ZERO_INIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_ZERO_INIT_32BIT )

# undef CANIF_START_SEC_VAR_ZERO_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_ZERO_INIT_32BIT )

# undef CANIF_STOP_SEC_VAR_ZERO_INIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_ZERO_INIT_8BIT )

# undef CANIF_START_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_ZERO_INIT_8BIT )

# undef CANIF_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED )

# undef CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED )

# undef CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_CODE )

# undef CANTP_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_CODE )

# undef CANTP_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_CONST_16BIT )

# undef CANTP_START_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_CONST_16BIT )

# undef CANTP_STOP_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_CONST_8BIT )

# undef CANTP_START_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_CONST_8BIT )

# undef CANTP_STOP_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_CONST_UNSPECIFIED )

# undef CANTP_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_CONST_UNSPECIFIED )

# undef CANTP_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_PBCFG )

# undef CANTP_START_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_PBCFG )

# undef CANTP_STOP_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_VAR_INIT_8BIT )

# undef CANTP_START_SEC_VAR_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_VAR_INIT_8BIT )

# undef CANTP_STOP_SEC_VAR_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_VAR_NOINIT_8BIT )

# undef CANTP_START_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_VAR_NOINIT_8BIT )

# undef CANTP_STOP_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_START_SEC_VAR_PBCFG )

# undef CANTP_START_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CANTP_STOP_SEC_VAR_PBCFG )

# undef CANTP_STOP_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_CODE )

# undef CAN_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_CODE )

# undef CAN_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_CODE_APPL )

# undef CAN_START_SEC_CODE_APPL
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_CODE_APPL )

# undef CAN_STOP_SEC_CODE_APPL
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_CONST_16BIT )

# undef CAN_START_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_CONST_16BIT )

# undef CAN_STOP_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_CONST_32BIT )

# undef CAN_START_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_CONST_32BIT )

# undef CAN_STOP_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_CONST_8BIT )

# undef CAN_START_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_CONST_8BIT )

# undef CAN_STOP_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_CONST_UNSPECIFIED )

# undef CAN_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_CONST_UNSPECIFIED )

# undef CAN_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_PBCFG )

# undef CAN_START_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_PBCFG )

# undef CAN_STOP_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_PBCFG_ROOT )

# undef CAN_START_SEC_PBCFG_ROOT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_PBCFG_ROOT )

# undef CAN_STOP_SEC_PBCFG_ROOT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_STATIC_CODE )

# undef CAN_START_SEC_STATIC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_STATIC_CODE )

# undef CAN_STOP_SEC_STATIC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_VAR_INIT_UNSPECIFIED )

# undef CAN_START_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_VAR_INIT_UNSPECIFIED )

# undef CAN_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_VAR_NOINIT_16BIT )

# undef CAN_START_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_VAR_NOINIT_16BIT )

# undef CAN_STOP_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_VAR_NOINIT_32BIT )

# undef CAN_START_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_VAR_NOINIT_32BIT )

# undef CAN_STOP_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_VAR_NOINIT_8BIT )

# undef CAN_START_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_VAR_NOINIT_8BIT )

# undef CAN_STOP_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef CAN_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_START_SEC_VAR_PBCFG )

# undef CAN_START_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CAN_STOP_SEC_VAR_PBCFG )

# undef CAN_STOP_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( COMM_START_SEC_CODE )

# undef COMM_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( COMM_STOP_SEC_CODE )

# undef COMM_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_START_SEC_CODE )

# undef DET_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_STOP_SEC_CODE )

# undef DET_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_START_SEC_CONST_UNSPECIFIED )

# undef DET_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_STOP_SEC_CONST_UNSPECIFIED )

# undef DET_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_START_SEC_VAR_INIT_UNSPECIFIED )

# undef DET_START_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_STOP_SEC_VAR_INIT_UNSPECIFIED )

# undef DET_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_START_SEC_VAR_NOINIT_8BIT )

# undef DET_START_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_STOP_SEC_VAR_NOINIT_8BIT )

# undef DET_STOP_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef DET_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( DET_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef DET_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( EEPDUMMY_FULL_START_SEC_CODE )

# undef EEPDUMMY_FULL_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( EEPDUMMY_FULL_STOP_SEC_CODE )

# undef EEPDUMMY_FULL_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( EEPDUMMY_START_SEC_VAR )
   # pragma ghs startdata
   # pragma ghs section bss=".EEPDATA"
# undef EEPDUMMY_START_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( EEPDUMMY_STOP_SEC_VAR )
# pragma ghs section
# pragma ghs enddata
# undef EEPDUMMY_STOP_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLAP_RAMCODE_START_SEC_CODE ) || \
    defined( FBLAP_RAMCODE_START_SEC_CODE_EXPORT )

# undef FBLAP_RAMCODE_START_SEC_CODE
# undef FBLAP_RAMCODE_START_SEC_CODE_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLAP_RAMCODE_STOP_SEC_CODE ) || \
    defined( FBLAP_RAMCODE_STOP_SEC_CODE_EXPORT )

# undef FBLAP_RAMCODE_STOP_SEC_CODE
# undef FBLAP_RAMCODE_STOP_SEC_CODE_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMAP_START_SEC_CODE )

# undef FBLBMAP_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMAP_STOP_SEC_CODE )

# undef FBLBMAP_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMAP_START_SEC_VAR )

# undef FBLBMAP_START_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMAP_STOP_SEC_VAR )

# undef FBLBMAP_STOP_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDRAP_START_SEC_CODE )

# undef FBLBMHDRAP_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDRAP_STOP_SEC_CODE )

# undef FBLBMHDRAP_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDR_BMHEADER_START_SEC_CONST )
# pragma ghs startdata
# pragma ghs section rodata=".FBLBMHEADERHDR"
# undef FBLBMHDR_BMHEADER_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDR_BMHEADER_STOP_SEC_CONST )
# pragma ghs section rodata=default
# pragma ghs enddata
# undef FBLBMHDR_BMHEADER_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDR_START_SEC_CODE )

# undef FBLBMHDR_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDR_STOP_SEC_CODE )

# undef FBLBMHDR_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDR_START_SEC_CONST )

# undef FBLBMHDR_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBMHDR_STOP_SEC_CONST )

# undef FBLBMHDR_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_HEADER_START_SEC_CONST )
# pragma ghs startdata
# pragma ghs section rodata=".FBLBMHEADER"
# undef FBLBM_HEADER_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_HEADER_STOP_SEC_CONST )
# pragma ghs section rodata=default
# pragma ghs enddata
# undef FBLBM_HEADER_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_MAIN_APPLSTART_START_SEC_CODE )

# undef FBLBM_MAIN_APPLSTART_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_MAIN_APPLSTART_STOP_SEC_CODE )

# undef FBLBM_MAIN_APPLSTART_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_MAIN_FBLSTART_START_SEC_CODE )

# undef FBLBM_MAIN_FBLSTART_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_MAIN_FBLSTART_STOP_SEC_CODE )

# undef FBLBM_MAIN_FBLSTART_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_MAIN_MAGICFLAG_START_SEC_VAR_NOINIT )
   # pragma ghs startdata
   # pragma ghs section bss=".FBLMAGIC"
# undef FBLBM_MAIN_MAGICFLAG_START_SEC_VAR_NOINIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_MAIN_MAGICFLAG_STOP_SEC_VAR_NOINIT )
   # pragma ghs section
   # pragma ghs enddata
# undef FBLBM_MAIN_MAGICFLAG_STOP_SEC_VAR_NOINIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_START_SEC_CODE )

# undef FBLBM_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_STOP_SEC_CODE )

# undef FBLBM_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_START_SEC_CONST )

# undef FBLBM_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_STOP_SEC_CONST )

# undef FBLBM_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_START_SEC_VAR )

# undef FBLBM_START_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLBM_STOP_SEC_VAR )

# undef FBLBM_STOP_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_APPL_CODE )

# undef FBLCW_START_SEC_APPL_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_APPL_CODE )

# undef FBLCW_STOP_SEC_APPL_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_CODE )
   # pragma ghs startdata
   # pragma ghs section text=".RAMCODE"
# undef FBLCW_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_CODE )
   # pragma ghs section
   # pragma ghs enddata
# undef FBLCW_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_CONST_16BIT )

# undef FBLCW_START_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_CONST_16BIT )

# undef FBLCW_STOP_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_CONST_32BIT )

# undef FBLCW_START_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_CONST_32BIT )

# undef FBLCW_STOP_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_CONST_64BIT )

# undef FBLCW_START_SEC_CONST_64BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_CONST_64BIT )

# undef FBLCW_STOP_SEC_CONST_64BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_CONST_8BIT )

# undef FBLCW_START_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_CONST_8BIT )

# undef FBLCW_STOP_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_CONST_UNSPECIFIED )

# undef FBLCW_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_CONST_UNSPECIFIED )

# undef FBLCW_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_PBCFG )

# undef FBLCW_START_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_PBCFG )

# undef FBLCW_STOP_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_INIT_UNSPECIFIED )

# undef FBLCW_START_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_INIT_UNSPECIFIED )

# undef FBLCW_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_NOINIT_16BIT )

# undef FBLCW_START_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_NOINIT_16BIT )

# undef FBLCW_STOP_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_NOINIT_32BIT )

# undef FBLCW_START_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_NOINIT_32BIT )

# undef FBLCW_STOP_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_NOINIT_64BIT )

# undef FBLCW_START_SEC_VAR_NOINIT_64BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_NOINIT_64BIT )

# undef FBLCW_STOP_SEC_VAR_NOINIT_64BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_NOINIT_8BIT )

# undef FBLCW_START_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_NOINIT_8BIT )

# undef FBLCW_STOP_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_NOINIT_BOOLEAN )

# undef FBLCW_START_SEC_VAR_NOINIT_BOOLEAN
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_NOINIT_BOOLEAN )

# undef FBLCW_STOP_SEC_VAR_NOINIT_BOOLEAN
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef FBLCW_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef FBLCW_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_PBCFG )

# undef FBLCW_START_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_PBCFG )

# undef FBLCW_STOP_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_ZERO_INIT_8BIT )

# undef FBLCW_START_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_ZERO_INIT_8BIT )

# undef FBLCW_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_START_SEC_VAR_ZERO_INIT_UNSPECIFIED )

# undef FBLCW_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLCW_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED )

# undef FBLCW_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLDIAG_RAMCODE_START_SEC_CODE )
   # pragma ghs startdata
   # pragma ghs section text=".RAMCODE"
# undef FBLDIAG_RAMCODE_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLDIAG_RAMCODE_STOP_SEC_CODE )
   # pragma ghs section
   # pragma ghs enddata
# undef FBLDIAG_RAMCODE_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLHEADER_START_SEC_CONST )
# pragma ghs startdata
# pragma ghs section rodata=".FBLHEADER"
# undef FBLHEADER_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLHEADER_STOP_SEC_CONST )
# pragma ghs section rodata=default
# pragma ghs enddata
# undef FBLHEADER_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLHW_START_SEC_CODE )

# undef FBLHW_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLHW_STOP_SEC_CODE )

# undef FBLHW_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLLIB_MEM_RAMCODE_START_SEC_CODE ) || \
    defined( FBLLIB_MEM_RAMCODE_START_SEC_CODE_EXPORT )
   # pragma ghs startdata
   # pragma ghs section text=".RAMCODE"
# undef FBLLIB_MEM_RAMCODE_START_SEC_CODE
# undef FBLLIB_MEM_RAMCODE_START_SEC_CODE_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLLIB_MEM_RAMCODE_STOP_SEC_CODE ) || \
    defined( FBLLIB_MEM_RAMCODE_STOP_SEC_CODE_EXPORT )
   # pragma ghs section
   # pragma ghs enddata
# undef FBLLIB_MEM_RAMCODE_STOP_SEC_CODE
# undef FBLLIB_MEM_RAMCODE_STOP_SEC_CODE_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLLIB_MEM_START_SEC_CONST )
   # pragma ghs startdata
   # pragma ghs section rodata=".RAMCONST"
# undef FBLLIB_MEM_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLLIB_MEM_STOP_SEC_CONST )
   # pragma ghs section
   # pragma ghs enddata
# undef FBLLIB_MEM_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLLIB_MEM_START_SEC_VAR ) || \
    defined( FBLLIB_MEM_START_SEC_VAR_EXPORT )

# undef FBLLIB_MEM_START_SEC_VAR
# undef FBLLIB_MEM_START_SEC_VAR_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLLIB_MEM_STOP_SEC_VAR ) || \
    defined( FBLLIB_MEM_STOP_SEC_VAR_EXPORT )

# undef FBLLIB_MEM_STOP_SEC_VAR
# undef FBLLIB_MEM_STOP_SEC_VAR_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLMIO_START_SEC_CODE )

# undef FBLMIO_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLMIO_STOP_SEC_CODE )

# undef FBLMIO_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLMIO_START_SEC_VAR )

# undef FBLMIO_START_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLMIO_STOP_SEC_VAR )

# undef FBLMIO_STOP_SEC_VAR
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLWD_INIT_START_SEC_CODE )

# undef FBLWD_INIT_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLWD_INIT_STOP_SEC_CODE )

# undef FBLWD_INIT_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLWD_RAMCODE_START_SEC_CODE )
# pragma ghs startdata
# pragma ghs section text=".RAMCODE"
# undef FBLWD_RAMCODE_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBLWD_RAMCODE_STOP_SEC_CODE )
# pragma ghs section
# pragma ghs enddata
# undef FBLWD_RAMCODE_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBL_APPLVECT_START_SEC_CONST )
# pragma ghs startdata
# pragma ghs section rodata=".APPLVECT"
# undef FBL_APPLVECT_START_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FBL_APPLVECT_STOP_SEC_CONST )
   # pragma ghs section
   # pragma ghs enddata
# undef FBL_APPLVECT_STOP_SEC_CONST
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FLASHCODE_START_SEC_VAR ) || \
    defined( FLASHCODE_START_SEC_VAR_EXPORT )
# pragma ghs startdata
# pragma ghs section bss=".FLASHDRV"
# undef FLASHCODE_START_SEC_VAR
# undef FLASHCODE_START_SEC_VAR_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( FLASHCODE_STOP_SEC_VAR ) || \
    defined( FLASHCODE_STOP_SEC_VAR_EXPORT )
   # pragma ghs section
   # pragma ghs enddata
# undef FLASHCODE_STOP_SEC_VAR
# undef FLASHCODE_STOP_SEC_VAR_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( MEMCPY_START_SEC_CODE )

# undef MEMCPY_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( MEMCPY_STOP_SEC_CODE )

# undef MEMCPY_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_BUFFER_VAR_NOINIT_8BIT )

# undef PDUR_START_SEC_BUFFER_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_BUFFER_VAR_NOINIT_8BIT )

# undef PDUR_STOP_SEC_BUFFER_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_CODE )

# undef PDUR_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_CODE )

# undef PDUR_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_CONST_16BIT )

# undef PDUR_START_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_CONST_16BIT )

# undef PDUR_STOP_SEC_CONST_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_CONST_32BIT )

# undef PDUR_START_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_CONST_32BIT )

# undef PDUR_STOP_SEC_CONST_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_CONST_8BIT )

# undef PDUR_START_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_CONST_8BIT )

# undef PDUR_STOP_SEC_CONST_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_CONST_UNSPECIFIED )

# undef PDUR_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_CONST_UNSPECIFIED )

# undef PDUR_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_PBCFG )

# undef PDUR_START_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_PBCFG )

# undef PDUR_STOP_SEC_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_NOINIT_16BIT )

# undef PDUR_START_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_NOINIT_16BIT )

# undef PDUR_STOP_SEC_VAR_NOINIT_16BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_NOINIT_32BIT )

# undef PDUR_START_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_NOINIT_32BIT )

# undef PDUR_STOP_SEC_VAR_NOINIT_32BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_NOINIT_8BIT )

# undef PDUR_START_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_NOINIT_8BIT )

# undef PDUR_STOP_SEC_VAR_NOINIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_PBCFG )

# undef PDUR_START_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_PBCFG )

# undef PDUR_STOP_SEC_VAR_PBCFG
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_ZERO_INIT_8BIT )

# undef PDUR_START_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_ZERO_INIT_8BIT )

# undef PDUR_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_START_SEC_VAR_ZERO_INIT_UNSPECIFIED )

# undef PDUR_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( PDUR_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED )

# undef PDUR_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( SECMWS_START_SEC_DATA ) || \
    defined( SECMWS_START_SEC_DATA_EXPORT )

# undef SECMWS_START_SEC_DATA
# undef SECMWS_START_SEC_DATA_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( SECMWS_STOP_SEC_DATA ) || \
    defined( SECMWS_STOP_SEC_DATA_EXPORT )

# undef SECMWS_STOP_SEC_DATA
# undef SECMWS_STOP_SEC_DATA_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( VSTDLIB_START_SEC_CODE )

# undef VSTDLIB_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( VSTDLIB_STOP_SEC_CODE )

# undef VSTDLIB_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WDTRIGGER_START_SEC_CODE ) || \
    defined( WDTRIGGER_START_SEC_CODE_EXPORT )
   # pragma ghs startdata
   # pragma ghs section text=".RAMCODE"
# undef WDTRIGGER_START_SEC_CODE
# undef WDTRIGGER_START_SEC_CODE_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WDTRIGGER_STOP_SEC_CODE ) || \
    defined( WDTRIGGER_STOP_SEC_CODE_EXPORT )
   # pragma ghs section
   # pragma ghs enddata
# undef WDTRIGGER_STOP_SEC_CODE
# undef WDTRIGGER_STOP_SEC_CODE_EXPORT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WRAPNV_START_SEC_CODE )

# undef WRAPNV_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WRAPNV_STOP_SEC_CODE )

# undef WRAPNV_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WRAPNV_START_SEC_CONST_UNSPECIFIED )

# undef WRAPNV_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WRAPNV_STOP_SEC_CONST_UNSPECIFIED )

# undef WRAPNV_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WRAPNV_START_SEC_VAR_NOINIT_UNSPECIFIED )

# undef WRAPNV_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( WRAPNV_STOP_SEC_VAR_NOINIT_UNSPECIFIED )

# undef WRAPNV_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( _CDD_START_SEC_CODE )

# undef _CDD_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( _CDD_STOP_SEC_CODE )

# undef _CDD_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( SECMPAR_START_SEC_DATA )

# undef SECMPAR_START_SEC_DATA
# undef FBL_MEMMAP_ERROR
#endif

#if defined( SECMPAR_STOP_SEC_DATA )

# undef SECMPAR_STOP_SEC_DATA
# undef FBL_MEMMAP_ERROR
#endif

#ifdef ECUABFEE_START_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_CODE
    #define START_SEC_CODE
#endif
#ifdef ECUABFEE_STOP_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

#ifdef ECUABFEE_START_SEC_CONST_8BIT

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_CONST_8BIT
    #define START_SEC_CONST_8BIT
#endif
#ifdef ECUABFEE_STOP_SEC_CONST_8BIT

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_CONST_8BIT
    #define STOP_SEC_CONST
#endif

#ifdef ECUABFEE_START_SEC_CONST_16BIT

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_CONST_16BIT
    #define START_SEC_CONST_16BIT
#endif
#ifdef ECUABFEE_STOP_SEC_CONST_16BIT

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_CONST_16BIT
    #define STOP_SEC_CONST
#endif

#ifdef ECUABFEE_START_SEC_CONST_32BIT

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_CONST_32BIT
    #define START_SEC_CONST_32BIT
#endif
#ifdef ECUABFEE_STOP_SEC_CONST_32BIT

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_CONST_32BIT
    #define STOP_SEC_CONST
#endif

#ifdef ECUABFEE_START_SEC_CONST_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef ECUABFEE_STOP_SEC_CONST_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#ifdef ECUABFEE_START_SEC_VAR_NOINIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_VAR_NOINIT_UNSPECIFIED
    #define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef ECUABFEE_STOP_SEC_VAR_NOINIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef ECUABFEE_START_SEC_VAR_FAST_INIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #define START_SEC_VAR_FAST_INIT_UNSPECIFIED
#endif
#ifdef ECUABFEE_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef ECUABFEE_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef MEMIF_START_SEC_CONST_8BIT

    # undef FBL_MEMMAP_ERROR
    #undef MEMIF_START_SEC_CONST_8BIT
    #define START_SEC_CONST_8BIT
#endif

#ifdef MEMIF_STOP_SEC_CONST_8BIT

    # undef FBL_MEMMAP_ERROR
    #undef MEMIF_STOP_SEC_CONST_8BIT
    #define STOP_SEC_CONST
#endif

#ifdef MEMIF_START_SEC_CONST_32BIT

    # undef FBL_MEMMAP_ERROR
    #undef MEMIF_START_SEC_CONST_32BIT
    #define START_SEC_CONST_32BIT
#endif

#ifdef MEMIF_STOP_SEC_CONST_32BIT

    # undef FBL_MEMMAP_ERROR
    #undef MEMIF_STOP_SEC_CONST_32BIT
    #define STOP_SEC_CONST
#endif

#ifdef MEMIF_START_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef MEMIF_START_SEC_CODE
    #define START_SEC_CODE
#endif

#ifdef MEMIF_STOP_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef MEMIF_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

#ifdef NVM_START_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_CODE
    #define START_SEC_CODE
#endif
#ifdef NVM_STOP_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

#ifdef NVM_START_SEC_CONST_8

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_CONST_8
    #define START_SEC_CONST_8BIT
#endif
#ifdef NVM_STOP_SEC_CONST_8

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_CONST_8
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_16

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_CONST_16
    #define START_SEC_CONST_16BIT
#endif
#ifdef NVM_STOP_SEC_CONST_16

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_CONST_16
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_CONST_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_DESCRIPTOR_TABLE

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_CONST_DESCRIPTOR_TABLE
    #define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE
    #define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_VAR_NOINIT_8

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_VAR_NOINIT_8
    #define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef NVM_STOP_SEC_VAR_NOINIT_8

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_VAR_NOINIT_8
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_NOINIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_VAR_NOINIT_UNSPECIFIED
    #define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_VAR_UNSPECIFIED
    #define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_VAR_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_FAST_8

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_VAR_FAST_8
    #define START_SEC_VAR_FAST_NOINIT_8BIT
#endif
#ifdef NVM_STOP_SEC_VAR_FAST_8

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_VAR_FAST_8
    #define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED

    # undef FBL_MEMMAP_ERROR
    #undef NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #define STOP_SEC_VAR
#endif

#if defined(VSTDLIB_START_SEC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef VSTDLIB_START_SEC_CODE
# define START_SEC_CODE
#endif
#if defined(VSTDLIB_STOP_SEC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef VSTDLIB_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_PUBLIC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_PUBLIC_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_PUBLIC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_PUBLIC_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_SCHEDULER_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_SCHEDULER_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_SCHEDULER_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_SCHEDULER_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_PRIVATE_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_PRIVATE_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_PRIVATE_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_PRIVATE_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_CODE_FAST)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_CODE_FAST
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_CODE_FAST)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_CODE_FAST
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_BUFFER_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_BUFFER_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_BUFFER_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_BUFFER_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_APPL_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_APPL_CODE
# define START_SEC_CODE
#endif
#if defined(FLS_STOP_SEC_APPL_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_APPL_CODE
# define STOP_SEC_CODE
#endif

#if defined(FLS_START_SEC_VAR_NOINIT_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_VAR_NOINIT_UNSPECIFIED
# define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_NOINIT_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_VAR_UNSPECIFIED
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_VAR_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_BOOLEAN)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_VAR_BOOLEAN
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_BOOLEAN)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_VAR_BOOLEAN
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_1BIT)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_VAR_1BIT
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_VAR_1BIT)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_VAR_1BIT
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_NOINIT_32)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_VAR_NOINIT_32
# define START_SEC_VAR_NOINIT_32BIT
#endif
#if defined(FLS_STOP_SEC_VAR_NOINIT_32)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_VAR_NOINIT_32
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_VAR_NOINIT_32BIT)
#
    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_VAR_NOINIT_32BIT
# define START_SEC_VAR_NOINIT_32BIT
#endif
#if defined(FLS_STOP_SEC_VAR_NOINIT_32BIT)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_VAR_NOINIT_32BIT
# define STOP_SEC_VAR
#endif

#if defined(FLS_START_SEC_DBTOC_DATA_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FLS_START_SEC_DBTOC_DATA_UNSPECIFIED
# define START_SEC_CONST_UNSPECIFIED
#endif
#if defined(FLS_STOP_SEC_DBTOC_DATA_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FLS_STOP_SEC_DBTOC_DATA_UNSPECIFIED
# define STOP_SEC_CONST
#endif

#if defined(FDL_START_SEC_PUBLIC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FDL_START_SEC_PUBLIC_CODE
# define START_SEC_CODE
#endif
#if defined(FDL_STOP_SEC_PUBLIC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef FDL_STOP_SEC_PUBLIC_CODE
# define STOP_SEC_CODE
#endif

#if defined(FDL_START_SEC_CONST_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
    #undef FDL_START_SEC_CONST_UNSPECIFIED
    #define START_SEC_CONST_UNSPECIFIED
#endif
#if defined(FDL_STOP_SEC_CONST_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
    #undef FDL_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SEC_CONST
#endif

#if defined(FDL_START_SEC_VAR_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FDL_START_SEC_VAR_UNSPECIFIED
# define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined(FDL_STOP_SEC_VAR_UNSPECIFIED)

    # undef FBL_MEMMAP_ERROR
# undef FDL_STOP_SEC_VAR_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined(CRC_START_SEC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef CRC_START_SEC_CODE
# define START_SEC_CODE
#endif
#if defined(CRC_STOP_SEC_CODE)

    # undef FBL_MEMMAP_ERROR
# undef CRC_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#ifdef CRC_START_SEC_CONST_8BIT

    # undef FBL_MEMMAP_ERROR
    #undef CRC_START_SEC_CONST_8BIT
    #define START_SEC_CONST_8BIT
#endif
#ifdef CRC_STOP_SEC_CONST_8BIT

    # undef FBL_MEMMAP_ERROR
    #undef CRC_STOP_SEC_CONST_8BIT
    #define STOP_SEC_CONST
#endif

#ifdef CRC_START_SEC_CONST_16BIT

    # undef FBL_MEMMAP_ERROR
    #undef CRC_START_SEC_CONST_16BIT
    #define START_SEC_CONST_16BIT
#endif
#ifdef CRC_STOP_SEC_CONST_16BIT

    # undef FBL_MEMMAP_ERROR
    #undef CRC_STOP_SEC_CONST_16BIT
    #define STOP_SEC_CONST
#endif

#ifdef CRC_START_SEC_CONST_32BIT

    # undef FBL_MEMMAP_ERROR
    #undef CRC_START_SEC_CONST_32BIT
    #define START_SEC_CONST_32BIT
#endif
#ifdef CRC_STOP_SEC_CONST_32BIT

    # undef FBL_MEMMAP_ERROR
    #undef CRC_STOP_SEC_CONST_32BIT
    #define STOP_SEC_CONST
#endif

 #ifdef MYCOM_BL_STATUS_MSG_START_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef MYCOM_BL_STATUS_MSG_START_SEC_CODE
    #define START_SEC_CODE
#endif
#ifdef MYCOM_BL_STATUS_MSG_STOP_SEC_CODE

    # undef FBL_MEMMAP_ERROR
    #undef MYCOM_BL_STATUS_MSG_STOP_SEC_CODE
    #define STOP_SEC_CODE
#endif

 #ifdef FLASH_DRIVER_START_SEC_CONST
    # pragma ghs startdata
    # pragma ghs section rodata=".roFlashDrvRom"
    # undef FBL_MEMMAP_ERROR
    # undef FLASH_DRIVER_START_SEC_CONST
#endif
#ifdef FLASH_DRIVER_STOP_SEC_CONST
    # pragma ghs section rodata=default
    # pragma ghs enddata
    # undef FBL_MEMMAP_ERROR
    # undef FLASH_DRIVER_STOP_SEC_CONST
#endif

#ifdef SECM_START_SEC_CODE
	
# undef FBL_MEMMAP_ERROR
#undef SECM_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef SECM_STOP_SEC_CODE
	
# undef FBL_MEMMAP_ERROR
#undef SECM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef SECM_START_SEC_CONST
	
# undef FBL_MEMMAP_ERROR
#undef SECM_START_SEC_CONST
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef SECM_STOP_SEC_CONST
	
# undef FBL_MEMMAP_ERROR
#undef SECM_STOP_SEC_CONST
#define STOP_SEC_CONST
#endif

#ifdef SECM_START_SEC_VAR
	
# undef FBL_MEMMAP_ERROR
#undef SECM_START_SEC_VAR
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef SECM_STOP_SEC_VAR
	
# undef FBL_MEMMAP_ERROR
#undef SECM_STOP_SEC_VAR
#define STOP_SEC_VAR
#endif

#ifdef CSM_START_SEC_CODE
	
# undef FBL_MEMMAP_ERROR
# undef CSM_START_SEC_CODE
# define START_SEC_CODE
#endif
#ifdef CSM_STOP_SEC_CODE
	
# undef FBL_MEMMAP_ERROR
# undef CSM_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#ifdef CSM_START_SEC_CONST_8BIT
# undef CSM_START_SEC_CONST_8BIT
# define START_SEC_CONST_8BIT
#endif

#ifdef CSM_STOP_SEC_CONST_8BIT
# undef CSM_STOP_SEC_CONST_8BIT
# define STOP_SEC_CONST
#endif

#ifdef CSM_START_SEC_CONST_UNSPECIFIED
	
# undef FBL_MEMMAP_ERROR
# undef CSM_START_SEC_CONST_UNSPECIFIED
# define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef CSM_STOP_SEC_CONST_UNSPECIFIED
	
# undef FBL_MEMMAP_ERROR
# undef CSM_STOP_SEC_CONST_UNSPECIFIED
# define STOP_SEC_CONST
#endif

#ifdef CSM_START_SEC_VAR_NOINIT_8BIT
	
# undef FBL_MEMMAP_ERROR
# undef CSM_START_SEC_VAR_NOINIT_8BIT
# define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef CSM_STOP_SEC_VAR_NOINIT_8BIT
	
# undef FBL_MEMMAP_ERROR
# undef CSM_STOP_SEC_VAR_NOINIT_8BIT
# define STOP_SEC_VAR
#endif

#ifdef CSM_START_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
# undef CSM_START_SEC_VAR_ZERO_INIT_8BIT
# define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef CSM_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
# undef CSM_STOP_SEC_VAR_ZERO_INIT_8BIT
# define STOP_SEC_VAR
#endif

#ifdef CSM_START_SEC_VAR_NOINIT_UNSPECIFIED
	
# undef FBL_MEMMAP_ERROR
# undef CSM_START_SEC_VAR_NOINIT_UNSPECIFIED
# define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef CSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
	
# undef FBL_MEMMAP_ERROR
# undef CSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#if defined( CRYIF_START_SEC_CONST_UNSPECIFIED )

# undef CRYIF_START_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CRYIF_STOP_SEC_CONST_UNSPECIFIED )

# undef CRYIF_STOP_SEC_CONST_UNSPECIFIED
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CRYIF_START_SEC_CODE )

# undef CRYIF_START_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CRYIF_STOP_SEC_CODE )

# undef CRYIF_STOP_SEC_CODE
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CRYIF_START_SEC_VAR_ZERO_INIT_8BIT )

# undef CRYIF_START_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( CRYIF_STOP_SEC_VAR_ZERO_INIT_8BIT )

# undef CRYIF_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef FBL_MEMMAP_ERROR
#endif

#if defined( MCALCRY_START_SEC_CODE )

# undef FBL_MEMMAP_ERROR
# undef MEMMAP_ERROR
# undef MCALCRY_START_SEC_CODE
#endif

#if defined( MCALCRY_STOP_SEC_CODE )

# undef FBL_MEMMAP_ERROR
# undef MEMMAP_ERROR
# undef MCALCRY_STOP_SEC_CODE
#endif

#if defined( FBL_MEMMAP_ERROR )
# error "Error in MemMap.h: MemMap section is not included!"
#endif

